const exampleGroups = async () => ({
  filters: {},
  competition: {
    id: 2018,
    area: {
      id: 2077,
      name: 'Europe',
    },
    name: 'European Championship',
    code: 'EC',
    plan: 'TIER_ONE',
    lastUpdated: '2020-09-10T13:51:03Z',
  },
  season: {
    id: 507,
    startDate: '2021-06-11',
    endDate: '2021-07-11',
    currentMatchday: 1,
    winner: null,
  },
  standings: [
    {
      stage: 'GROUP_STAGE',
      type: 'TOTAL',
      group: 'GROUP_A',
      table: [
        {
          position: 1,
          team: {
            id: 784,
            name: 'Italy',
            crestUrl: 'https://crests.football-data.org/784.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 3,
          goalsAgainst: 0,
          goalDifference: 3,
        },
        {
          position: 2,
          team: {
            id: 788,
            name: 'Switzerland',
            crestUrl: 'https://crests.football-data.org/788.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 1,
          lost: 0,
          points: 1,
          goalsFor: 1,
          goalsAgainst: 1,
          goalDifference: 0,
        },
        {
          position: 3,
          team: {
            id: 833,
            name: 'Wales',
            crestUrl: 'https://crests.football-data.org/833.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 1,
          lost: 0,
          points: 1,
          goalsFor: 1,
          goalsAgainst: 1,
          goalDifference: 0,
        },
        {
          position: 4,
          team: {
            id: 803,
            name: 'Turkey',
            crestUrl: 'https://crests.football-data.org/803.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 3,
          goalDifference: -3,
        },
      ],
    },
    {
      stage: 'GROUP_STAGE',
      type: 'TOTAL',
      group: 'GROUP_B',
      table: [
        {
          position: 1,
          team: {
            id: 805,
            name: 'Belgium',
            crestUrl: 'https://crests.football-data.org/805.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 3,
          goalsAgainst: 0,
          goalDifference: 3,
        },
        {
          position: 2,
          team: {
            id: 1976,
            name: 'Finland',
            crestUrl: 'https://crests.football-data.org/1976.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 1,
          goalsAgainst: 0,
          goalDifference: 1,
        },
        {
          position: 3,
          team: {
            id: 782,
            name: 'Denmark',
            crestUrl: 'https://crests.football-data.org/782.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 1,
          goalDifference: -1,
        },
        {
          position: 4,
          team: {
            id: 808,
            name: 'Russia',
            crestUrl: 'https://crests.football-data.org/808.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 3,
          goalDifference: -3,
        },
      ],
    },
    {
      stage: 'GROUP_STAGE',
      type: 'TOTAL',
      group: 'GROUP_C',
      table: [
        {
          position: 1,
          team: {
            id: 816,
            name: 'Austria',
            crestUrl: 'https://crests.football-data.org/816.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 3,
          goalsAgainst: 1,
          goalDifference: 2,
        },
        {
          position: 2,
          team: {
            id: 8601,
            name: 'Netherlands',
            crestUrl: 'https://crests.football-data.org/8601.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 3,
          goalsAgainst: 2,
          goalDifference: 1,
        },
        {
          position: 3,
          team: {
            id: 790,
            name: 'Ukraine',
            crestUrl: 'https://crests.football-data.org/790.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 2,
          goalsAgainst: 3,
          goalDifference: -1,
        },
        {
          position: 4,
          team: {
            id: 1977,
            name: 'North Macedonia',
            crestUrl: 'https://crests.football-data.org/1977.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 3,
          goalDifference: -2,
        },
      ],
    },
    {
      stage: 'GROUP_STAGE',
      type: 'TOTAL',
      group: 'GROUP_D',
      table: [
        {
          position: 1,
          team: {
            id: 798,
            name: 'Czech Republic',
            crestUrl: 'https://crests.football-data.org/798.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 0,
          goalDifference: 2,
        },
        {
          position: 2,
          team: {
            id: 770,
            name: 'England',
            crestUrl: 'https://crests.football-data.org/770.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 1,
          goalsAgainst: 0,
          goalDifference: 1,
        },
        {
          position: 3,
          team: {
            id: 799,
            name: 'Croatia',
            crestUrl: 'https://crests.football-data.org/799.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 1,
          goalDifference: -1,
        },
        {
          position: 4,
          team: {
            id: 8873,
            name: 'Scotland',
            crestUrl: 'https://crests.football-data.org/814.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 2,
          goalDifference: -2,
        },
      ],
    },
    {
      stage: 'GROUP_STAGE',
      type: 'TOTAL',
      group: 'GROUP_E',
      table: [
        {
          position: 1,
          team: {
            id: 768,
            name: 'Slovakia',
            crestUrl: 'https://crests.football-data.org/768.svg',
          },
          playedGames: 1,
          form: null,
          won: 1,
          draw: 0,
          lost: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 1,
          goalDifference: 1,
        },
        {
          position: 2,
          team: {
            id: 760,
            name: 'Spain',
            crestUrl: 'https://crests.football-data.org/760.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 1,
          lost: 0,
          points: 1,
          goalsFor: 0,
          goalsAgainst: 0,
          goalDifference: 0,
        },
        {
          position: 3,
          team: {
            id: 792,
            name: 'Sweden',
            crestUrl: 'https://crests.football-data.org/792.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 1,
          lost: 0,
          points: 1,
          goalsFor: 0,
          goalsAgainst: 0,
          goalDifference: 0,
        },
        {
          position: 4,
          team: {
            id: 794,
            name: 'Poland',
            crestUrl: 'https://crests.football-data.org/794.svg',
          },
          playedGames: 1,
          form: null,
          won: 0,
          draw: 0,
          lost: 1,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 2,
          goalDifference: -1,
        },
      ],
    },
    {
      stage: 'GROUP_STAGE',
      type: 'TOTAL',
      group: 'GROUP_F',
      table: [
        {
          position: 1,
          team: {
            id: 773,
            name: 'France',
            crestUrl: 'https://crests.football-data.org/773.svg',
          },
          playedGames: 0,
          form: null,
          won: 0,
          draw: 0,
          lost: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 0,
          goalDifference: 0,
        },
        {
          position: 2,
          team: {
            id: 759,
            name: 'Germany',
            crestUrl: 'https://crests.football-data.org/759.svg',
          },
          playedGames: 0,
          form: null,
          won: 0,
          draw: 0,
          lost: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 0,
          goalDifference: 0,
        },
        {
          position: 3,
          team: {
            id: 827,
            name: 'Hungary',
            crestUrl: 'https://crests.football-data.org/827.svg',
          },
          playedGames: 0,
          form: null,
          won: 0,
          draw: 0,
          lost: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 0,
          goalDifference: 0,
        },
        {
          position: 4,
          team: {
            id: 765,
            name: 'Portugal',
            crestUrl: 'https://crests.football-data.org/765.svg',
          },
          playedGames: 0,
          form: null,
          won: 0,
          draw: 0,
          lost: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 0,
          goalDifference: 0,
        },
      ],
    },
  ],
});

export default exampleGroups;
