const exampleTeam = async () => ({
  id: 8601,
  area: {
    id: 2163,
    name: 'Netherlands',
  },
  activeCompetitions: [
    {
      id: 2018,
      area: {
        id: 2077,
        name: 'Europe',
      },
      name: 'European Championship',
      code: 'EC',
      plan: 'TIER_ONE',
      lastUpdated: '2020-09-10T13:51:03Z',
    },
    {
      id: 2007,
      area: {
        id: 2077,
        name: 'Europe',
      },
      name: 'WC Qualification',
      code: null,
      plan: 'TIER_FOUR',
      lastUpdated: '2021-04-01T13:45:02Z',
    },
  ],
  name: 'Netherlands',
  shortName: 'Netherlands',
  tla: 'NED',
  crestUrl: 'https://crests.football-data.org/8601.svg',
  address: 'Woudenbergseweg 56-58 / Postbus 515 Zeist 3700 AM',
  phone: '+31 (343) 499201',
  website: 'http://www.knvb.nl',
  email: 'concern@knvb.nl',
  founded: 1889,
  clubColors: 'Orange / White / Blue',
  venue: 'Johan Cruyff ArenA',
  squad: [
    {
      id: 1848,
      name: 'Marten de Roon',
      position: 'Midfielder',
      dateOfBirth: '1991-03-29T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 15,
      role: 'PLAYER',
    },
    {
      id: 2053,
      name: 'Stefan de Vrij',
      position: 'Defender',
      dateOfBirth: '1992-02-05T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 6,
      role: 'PLAYER',
    },
    {
      id: 7417,
      name: 'Denzel Dumfries',
      position: 'Defender',
      dateOfBirth: '1996-04-18T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 22,
      role: 'PLAYER',
    },
    {
      id: 7452,
      name: 'Luuk de Jong',
      position: 'Attacker',
      dateOfBirth: '1990-08-27T00:00:00Z',
      countryOfBirth: 'Switzerland',
      nationality: 'Netherlands',
      shirtNumber: 9,
      role: 'PLAYER',
    },
    {
      id: 7457,
      name: 'Donyell Malen',
      position: 'Attacker',
      dateOfBirth: '1999-01-19T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 18,
      role: 'PLAYER',
    },
    {
      id: 7459,
      name: 'Cody Gakpo',
      position: 'Attacker',
      dateOfBirth: '1999-05-07T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 26,
      role: 'PLAYER',
    },
    {
      id: 7478,
      name: 'Steven Berghuis',
      position: 'Attacker',
      dateOfBirth: '1991-12-19T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 7,
      role: 'PLAYER',
    },
    {
      id: 7547,
      name: 'Joël Veltman',
      position: 'Defender',
      dateOfBirth: '1992-01-15T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 2,
      role: 'PLAYER',
    },
    {
      id: 7549,
      name: 'Matthijs de Ligt',
      position: 'Defender',
      dateOfBirth: '1999-08-12T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 3,
      role: 'PLAYER',
    },
    {
      id: 7559,
      name: 'Frenkie de Jong',
      position: 'Midfielder',
      dateOfBirth: '1997-05-12T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 21,
      role: 'PLAYER',
    },
    {
      id: 7675,
      name: 'Marco Bizot',
      position: 'Goalkeeper',
      dateOfBirth: '1991-03-10T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 23,
      role: 'PLAYER',
    },
    {
      id: 7679,
      name: 'Owen Wijndal',
      position: 'Defender',
      dateOfBirth: '1999-11-28T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 5,
      role: 'PLAYER',
    },
    {
      id: 7693,
      name: 'Teun Koopmeiners',
      position: 'Midfielder',
      dateOfBirth: '1998-02-28T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 24,
      role: 'PLAYER',
    },
    {
      id: 7697,
      name: 'Wout Weghorst',
      position: 'Attacker',
      dateOfBirth: '1992-08-07T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 19,
      role: 'PLAYER',
    },
    {
      id: 7822,
      name: 'Maarten Stekelenburg',
      position: 'Goalkeeper',
      dateOfBirth: '1982-09-22T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 1,
      role: 'PLAYER',
    },
    {
      id: 7841,
      name: 'Davy Klaassen',
      position: 'Midfielder',
      dateOfBirth: '1993-02-21T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 14,
      role: 'PLAYER',
    },
    {
      id: 7871,
      name: 'Georginio Wijnaldum',
      position: 'Midfielder',
      dateOfBirth: '1990-11-11T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 8,
      role: 'PLAYER',
    },
    {
      id: 7899,
      name: 'Daley Blind',
      position: 'Defender',
      dateOfBirth: '1990-03-09T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 17,
      role: 'PLAYER',
    },
    {
      id: 8146,
      name: 'Patrick van Aanholt',
      position: 'Defender',
      dateOfBirth: '1990-08-29T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 12,
      role: 'PLAYER',
    },
    {
      id: 8240,
      name: 'Nathan Aké',
      position: 'Defender',
      dateOfBirth: '1995-02-18T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 4,
      role: 'PLAYER',
    },
    {
      id: 8258,
      name: 'Tim Krul',
      position: 'Goalkeeper',
      dateOfBirth: '1988-04-03T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 13,
      role: 'PLAYER',
    },
    {
      id: 8472,
      name: 'Memphis Depay',
      position: 'Attacker',
      dateOfBirth: '1994-02-13T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 10,
      role: 'PLAYER',
    },
    {
      id: 11600,
      name: 'Frank de Boer',
      position: 'Defender',
      dateOfBirth: '1970-05-15T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: null,
      role: 'COACH',
    },
    {
      id: 16148,
      name: 'Quincy Promes',
      position: 'Attacker',
      dateOfBirth: '1992-01-04T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 11,
      role: 'PLAYER',
    },
    {
      id: 81793,
      name: 'Ryan Gravenberch',
      position: 'Midfielder',
      dateOfBirth: '2002-05-16T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 16,
      role: 'PLAYER',
    },
    {
      id: 98816,
      name: 'Jurrien Timber',
      position: 'Defender',
      dateOfBirth: '2001-06-17T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 25,
      role: 'PLAYER',
    },
  ],
  lastUpdated: '2021-05-28T18:49:20Z',
});

export default exampleTeam;
